export type Product = {
  id: number;
  title: string;
  price: number;
  gender: "M" | "F";
  type: "Casual" | "Corporate";
  image: string;
  description?: string;
  favourite: boolean;
  addtocart: boolean;
};

export const products: Product[] = [
  {
    id: 1,
    title: "Men Classic Shoe 1",
    price: 120,
    gender: "M",
    type: "Casual",
    image: "/images/men1.jpg",
    description: "A stylish comfortable shoe perfect for everyday wear.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 2,
    title: "Men Classic Shoe 2",
    price: 125,
    gender: "M",
    type: "Corporate",
    image: "/images/men2.jpg",
    description: "Elegant design for the office or formal events.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 3,
    title: "Men Classic Shoe 3",
    price: 118,
    gender: "M",
    type: "Casual",
    image: "/images/men3.jpg",
    description: "Casual men's shoe, perfect for everyday use.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 4,
    title: "Men Classic Shoe 4",
    price: 130,
    gender: "M",
    type: "Corporate",
    image: "/images/men4.jpg",
    description: "Corporate style footwear that exudes professionalism.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 5,
    title: "Men Classic Shoe 5",
    price: 135,
    gender: "M",
    type: "Casual",
    image: "/images/men5.jpg",
    description: "Comfort focused design for long hours on your feet.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 6,
    title: "Men Classic Shoe 6",
    price: 128,
    gender: "M",
    type: "Corporate",
    image: "/images/men6.jpg",
    description: "Premium materials meet classic corporate elegance.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 7,
    title: "Men Classic Shoe 7",
    price: 119,
    gender: "M",
    type: "Casual",
    image: "/images/men7.jpg",
    description: "Everyday casual shoe with durable construction.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 8,
    title: "Men Classic Shoe 8",
    price: 140,
    gender: "M",
    type: "Corporate",
    image: "/images/men8.jpg",
    description: "Business-ready shoe with a modern twist.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 9,
    title: "Men Classic Shoe 9",
    price: 122,
    gender: "M",
    type: "Casual",
    image: "/images/men9.jpg",
    description: "Lightweight and breathable for busy days.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 10,
    title: "Men Classic Shoe 10",
    price: 138,
    gender: "M",
    type: "Corporate",
    image: "/images/men10.jpg",
    description: "Sophisticated corporate shoe with a sleek finish.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 11,
    title: "Men Classic Shoe 11",
    price: 126,
    gender: "M",
    type: "Casual",
    image: "/images/men11.jpg",
    description: "Retro casual design updated for today.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 12,
    title: "Men Classic Shoe 12",
    price: 132,
    gender: "M",
    type: "Corporate",
    image: "/images/men12.jpg",
    description: "Quality craftsmanship tailored for corporate settings.",
    favourite: false,
    addtocart: false,
  },

  {
    id: 13,
    title: "Women Elegant Shoe 1",
    price: 110,
    gender: "F",
    type: "Casual",
    image: "/images/women1.jpg",
    description: "Elegant casual shoe designed for comfort and style.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 14,
    title: "Women Elegant Shoe 2",
    price: 115,
    gender: "F",
    type: "Corporate",
    image: "/images/women2.jpg",
    description: "Classy corporate shoe suitable for the modern professional.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 15,
    title: "Women Elegant Shoe 3",
    price: 108,
    gender: "F",
    type: "Casual",
    image: "/images/women3.jpg",
    description: "Everyday comfort with a touch of feminine flair.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 17,
    title: "Women Elegant Shoe 5",
    price: 118,
    gender: "F",
    type: "Casual",
    image: "/images/women5.jpg",
    description: "Stylish casual option built for all-day wear.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 18,
    title: "Women Elegant Shoe 6",
    price: 122,
    gender: "F",
    type: "Corporate",
    image: "/images/women6.jpg",
    description: "Professional design crafted from premium materials.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 19,
    title: "Women Elegant Shoe 7",
    price: 116,
    gender: "F",
    type: "Casual",
    image: "/images/women7.jpg",
    description: "Lightweight and breathable for casual outings.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 20,
    title: "Women Elegant Shoe 8",
    price: 125,
    gender: "F",
    type: "Corporate",
    image: "/images/women8.jpg",
    description: "Sleek corporate silhouette with modern details.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 21,
    title: "Women Elegant Shoe 9",
    price: 117,
    gender: "F",
    type: "Casual",
    image: "/images/women9.jpg",
    description: "Comfort-first design balancing style and support.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 22,
    title: "Women Elegant Shoe 10",
    price: 130,
    gender: "F",
    type: "Corporate",
    image: "/images/women10.jpg",
    description: "Corporate elegance with a feminine touch.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 23,
    title: "Women Elegant Shoe 11",
    price: 119,
    gender: "F",
    type: "Casual",
    image: "/images/women11.jpg",
    description: "Casual and chic, perfect for weekend wear.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 24,
    title: "Women Elegant Shoe 12",
    price: 124,
    gender: "F",
    type: "Corporate",
    image: "/images/women12.jpg",
    description: "Timeless corporate shoe built for performance.",
    favourite: false,
    addtocart: false,
  },
  {
    id: 25,
    title: "Women Elegant Shoe 13",
    price: 129,
    gender: "F",
    type: "Casual",
    image: "/images/women13.jpg",
    description: "Fresh casual design that pairs with any outfit.",
    favourite: false,
    addtocart: false,
  },
];
